# Basic
title: RLWB
subtitle: 前途似海  来日方长
welcome_message: <a href="https://github.com/rlwb" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="https://item.taobao.com/item.htm?spm=686.1000925.0.0.BiEjdx&id=538655619568">@rlwb</a>

url: "https://item.taobao.com/item.htm?_u=n1nag89e6bba&id=538633523652"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 文章
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 购买, description: 店铺, url: 'https://item.taobao.com/item.htm?_u=n1nag89e6bba&id=538633523652'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: rlwb-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 3218840434
    github: rlwb
    twitter: rlwb1017669154
    gplus: 114448230754493660354
    mail: rlwb1017669154@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
